version: '3.8'

services:
  backend:
    build: ./backend
    depends_on:
      - mongo
    ports:
      - '8000:8000'

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - '80:80'

  mongo:
    image: mongo
    restart: always
    hostname: annotator_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    volumes:
      - ./data/mongo:/data/db
      - ./data/mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
